### ISSUE TITLE
Allow space to be configured via yaml file

### ISSUE THREAD

**Issue by Scott-Graham-Bose** [scikit-optimize/scikit-optimize#651]
Would it be of value to support reading in the space configuration via a yaml file?

what I'm imagining would have a yaml file something like this:
```    
- Real:
       low: 0.0001
       high: 1
       prior: log-uniform
       name: learning_rate
- Categorical:
       categories: [8, 16, 32]
       name: batch_size
```

and then being able to use it like this:
```
from skopt.utils import use_named_args

@use_named_args('path/to/config.yml')
```

or potentially with a separate method
``` 
from skopt.utils import load_space

space = load_space('path/to/config.yml')
```

happy to contribute if this is worthwhile and would fit in to common use cases beyond my own.
