### ISSUE TITLE
`Space.from_yaml()` should parse the `name`

### ISSUE THREAD

**Issue by sotte** [scikit-optimize/scikit-optimize#758]
The `name` attribute in yaml files is ignored when creating a `Space` instance with `from_yaml()` and I think it shouldn't.

Example:
```yaml
# space.yaml
Space
    - Real:
        low: 0.00001
        high: 0.1
        name: lr
```
```python
space = Space.from_yaml("space.yaml")
print(space)
# Space([Real(low=1e-05, high=0.1, prior='uniform', transform='identity')])
```
